=== bisdn/un-orchestrator/name-resolver/config/network-functions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- definition of attributes -->
<xsd:attribute name="name">
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="([a-z]|[A-Z]|[0-9]|_|-)+"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>

<xsd:attribute name="type">	
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="dpdk" />
			<xsd:enumeration value="docker" />
			<xsd:enumeration value="kvm" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>

<xsd:attribute name="location">	
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="local" />
			<xsd:enumeration value="remote" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>

<!-- definition of elements -->
<xsd:element name="network-functions">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="network-function" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="implementation" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute ref="type" use="required"/>
								<xsd:attribute name="uri" type="xsd:string" use="required"/>
								<xsd:attribute name="cores" type="xsd:string"/> <!-- required for DPDK -->
								<xsd:attribute ref="location"/> <!-- required for DPDK -->
								<!-- 
									FIXME: is it possible to specify "cores" and "location" only if "type"
									is DPDK?
								-->
							</xsd:complexType>
						</xsd:element>	
					</xsd:sequence>
					<xsd:attribute ref="name" use="required"/>
					<!-- TODO: put num-ports mandatory! -->
					<xsd:attribute name="num-ports" type="xsd:integer"/>
					<xsd:attribute name="description" type="xsd:string" use="required"/>
				</xsd:complexType>
			</xsd:element> 
		</xsd:sequence>
	</xsd:complexType>
	<xsd:unique name="unique-network-function">
		<xsd:selector xpath="network-functions/network-function" />
		<xsd:field xpath="@name" />
	</xsd:unique>
</xsd:element>


</xsd:schema>

=== bisdn/un-orchestrator/name-resolver/config/example.xml
<?xml version="1.0" encoding="UTF-8"?>

<network-functions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                 xsi:noNamespaceSchemaLocation="network-functions.xsd">
                 
	<!--
		This is an example of configuration file for the name-resolver. For each
		network function name, it contains a list of possible implementations for
		that network function. 
		
		An implementation can be:
		* a docker container
		* a dpdk (secondary) process
		* a kvm virtual machine
		
		In case of docker container, the file specifies the URI from which the
		image of this container can be downloaded. Note that it must refer to
		a docker registry.
		
		In case of dpdk (secondary) process, the file specifies the URI from which
		the executable can be retrieved and the number of cores required by the
		network function. Since the URI can be a web URL or a path on the local file
		system, the file also specifies to interpretate the URI through the attribute
		location.
		
		In case of KVM virtual machine, the file specifies the URI from which the
		image of the virtual machine can be retrieved. It is a path on the local
		file system.
		Alternatively, the URI can point to an XML Libvirt doamin definition which
		the orchestrator uses as a template in which it adds or updates the
		network interfaces, etc. 
	-->

	<network-function name="example">
		<!-- Several implementations are available for this network function -->
		<implementation type="docker" uri="localhost:5000/example"/>
		<implementation type="dpdk" uri="https://nf_repository.com/example" cores="1" location="remote"/>
		<implementation type="dpdk" uri="/home/nf_repository/dpdk/example" cores="1" location="local"/>
		<implementation type="kvm" uri="/home/nf_repository/kvm/example.qcow2"/>
	</network-function>

	<network-function name="usvhost_example">
		<!-- Point to a Libvirt XML domain template -->
		<implementation type="kvm" uri="/home/nf_repository/kvm/kvm_usvhost_vnf.xml"/>
	</network-function>
	
	<network-function name="firewall">
		<!-- Only a docker implementation is available for this network function -->
		<implementation type="docker" uri="localhost:5000/iptables"/>
	</network-function>
   
	<network-function name="dpi">
		<!-- Only a DPDK implementaion is available for this network funcion -->
		<implementation type="dpdk" uri="../NFs/dpdk/dpi/build/dpi" cores="1" location="local"/>
	</network-function>

	<!-- my network-function examples -->
	<network-function name="VNFExample">
		<!-- Only a VNF implementation is available for this network function -->
		<implementation type="dpdk" uri="/home/nf_repository/dpdk/example" cores="1" location="remote"/>
	</network-function>
	<network-function name="VNFExample1">
		<!-- Only a VNF implementation is available for this network function -->
		<implementation type="dpdk" uri="/home/nf_repository/dpdk/example" cores="1" location="local"/>
	</network-function>

	<network-function name="bridge">
		<!-- Only a docker implementation is available for this network function -->
		<implementation type="docker" uri="simple_bridge"/>
	</network-function>

</network-functions>
