=== bisdn/un-orchestrator/orchestrator/config/universal-node-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- definition of attributes -->

<xsd:attribute name="type">	
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ethernet" />
			<xsd:enumeration value="wifi" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>

<xsd:attribute name="side">	
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="edge"/>
			<xsd:enumeration value="core"/>
			<xsd:enumeration value="none"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>

<xsd:attribute name="unit">	
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="MB"/>
			<xsd:enumeration value="GB"/>
			<xsd:enumeration value="TB"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>

<xsd:attribute name="port-type">	
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="port-abstract"/>
			<xsd:enumeration value="port-sap"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>


<!-- definition of elements -->
<xsd:element name="universal-node">
	<xsd:complexType>
		<xsd:all>
		
			<xsd:element name="resources" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="cpu" minOccurs="1" maxOccurs="1">		
							<xsd:complexType>
								<xsd:attribute name="amount" type="xsd:integer" use="required"/> 
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="memory" minOccurs="1" maxOccurs="1">	
							<xsd:complexType>
								<xsd:attribute name="amount" type="xsd:integer" use="required"/> 
								<xsd:attribute ref="unit" use="required"/> 
							</xsd:complexType>						
						</xsd:element>
						<xsd:element name="storage" minOccurs="1" maxOccurs="1">		
							<xsd:complexType>
								<xsd:attribute name="amount" type="xsd:integer" use="required"/>						
								<xsd:attribute ref="unit" use="required"/> 
							</xsd:complexType>
						</xsd:element>					
					</xsd:all>	
				</xsd:complexType>
			</xsd:element> <!-- End <resources> -->

			<xsd:element name="ports" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>				
					
						<xsd:element name="port" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
						
									<xsd:element name="virtualized" minOccurs="1" maxOccurs="1">
										<xsd:complexType>
											<xsd:attribute name="as" type="xsd:string" use="required"/>
											<xsd:attribute ref="port-type" use="required"/>
										</xsd:complexType>
									</xsd:element> <!-- End <virtualized> -->
																		
								</xsd:sequence>
								
								<xsd:attribute name="name" type="xsd:string" use="required"/>
								<xsd:attribute ref="type" use="required"/>
								<xsd:attribute ref="side" use="required"/>
								
							</xsd:complexType>
						</xsd:element> <!-- End <element> -->
						
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element> <!-- End <ports> -->
	
		</xsd:all>
	</xsd:complexType>
		
	<xsd:unique name="unique-physical-port">
		<xsd:selector xpath="physical-ports/port" />
		<xsd:field xpath="@name" />
	</xsd:unique>
	<!-- TODO: the "as" attribute must be unique! -->
	
</xsd:element>

</xsd:schema>

=== bisdn/un-orchestrator/orchestrator/config/universal-node-example.xml
<?xml version="1.0" encoding="UTF-8"?>

<universal-node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                 xsi:noNamespaceSchemaLocation="universal-node-schema.xsd">

	<resources>
		<cpu amount="10"/>
		<memory amount="32" unit="GB"/>
		<storage amount="5" unit="TB"/>
		
		<!--
			Values for "unit":
			* MB
			* GB
			* TB
		-->
		
	</resources>	

	<ports>
		<port name="10ge0" type="ethernet" side="edge">
			<virtualized as="OVS-north external port" port-type="port-sap"/>
		</port>
		<port name="10ge1" type="ethernet" side="core">
			<virtualized as="OVS-south external port" port-type="port-sap"/>
		</port>
		
		<!-- 
			Values for "type":
			* ethernet
			* wifi
			
			Note that not all the vSwitches supports DPDK ports.
		
			Values for "side":
			* edge
			* core
			* none
			
			Values for "port-type":
			* port-abstract
			* port-type
		-->	
		
	</ports>	

</universal-node>
